[[headers]]
  for = "/data/*.json"
  [headers.values]
    Content-Type = "application/json"
[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200